title: "GUIDE-LLM"
description: "Reporting Checklist for Studies with Large Language Models in the Behavioral and Social Sciences"
url: "https://sfeuerriegel.github.io"
baseurl: "/llm-checklist"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false

markdown: kramdown
kramdown:
  input: GFM

# Navigation menu at top
header:
  overlay_color: false
  overlay_filter: false
  overlay_image: false
  show_nav: true

main:
  - title: "Home"
    url: /
  - title: "Checklist"
    url: /checklist/
  - title: "Why"
    url: /why/
  - title: "How to Use"
    url: /how-to-use/
  - title: "Extensions"
    url: /extensions/
  - title: "Updates"
    url: /updates/
